### ISSUE TITLE
Recursive option doesn't preserve hierarchy

### ISSUE THREAD

**Issue by nordurljosahvida** [ldidry/gmail-mbox-to-imap#1]
The new -r option introduced in v1.3 does recurse into local directories but not recreate the same structure on the imap server. Thanks for the great work!

**Comment by nordurljosahvida** [comment]
Wrong repo, very sorry for the mistake!

**Comment by ldidry** [comment]
No pb.

**Comment by nordurljosahvida** [comment]
Thank you
